Smote_fasttext_autoencoding_features

In [ ]:
from google.colab import drive
from google.colab import files

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd 
import numpy as np 
from imblearn.over_sampling import SMOTE 
from sklearn.model_selection import KFold
from sklearn import metrics
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.preprocessing import MultiLabelBinarizer

**Models**

In [3]:
def Decision_tree_classifier(X_train, y_train, X_test, y_test):
  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(class_weight = "balanced")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("Decision Tree Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Decision Tree F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [4]:
def GNB_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  gnb = GaussianNB()

  #Train the model using the training sets
  gnb.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = gnb.predict(X_test)

  print("Gaussian Naive Bayes Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gaussian Naive Bayes F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [5]:
def KNN_classifier (X_train, y_train, X_test, y_test):
  #Create KNN Classifier
  knn = KNeighborsClassifier(n_neighbors=5)

  #Train the model using the training sets
  knn.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = knn.predict(X_test)

  print("KNN Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("KNN F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [6]:
def svm_classifier (X_train, y_train, X_test, y_test):
  #Create a Support Vector Machine Classifier
  clf = svm.SVC(kernel='linear', class_weight = "balanced") # Linear Kernel

  #Train the model using the training sets
  clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("SVM Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("SVM F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [7]:
def random_forest_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  clf=RandomForestClassifier(n_estimators=100, class_weight = "balanced")

  #Train the model using the training sets y_pred=clf.predict(X_test)
  clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred=clf.predict(X_test)
  print("RF Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("RF F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [8]:
def ada_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  abc = AdaBoostClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = abc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Ada-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Ada-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [9]:
def gradient_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  gbc = GradientBoostingClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = gbc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Gradient-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gradient-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [10]:
def perceptron_classifier (X_train, y_train, X_test, y_test):
  p = Perceptron(random_state=150)
  p.fit(X_train, y_train)
  predictions_train = p.predict(X_train)
  predictions_test = p.predict(X_test)
  train_score = accuracy_score(predictions_train, y_train)
  #print("score on train data: ", train_score)
  test_score = f1_score(predictions_test, y_test, average='weighted' )
  print("Perceptron F1 score:", test_score)

In [11]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smoteon_autoencoding_features/data.csv"
df3 = pd.read_csv(path)
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,Level 5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,Level 5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,Level 5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",Level 5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Level 2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [12]:
df3.iloc[:,1].replace(['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'],
                        [1, 2, 3, 4, 5], inplace=True)

In [13]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [14]:
#define bins
bins = [0,2,4,5]
#name of the group 
group_names = ['Low', 'Moderate', 'High']
df3['Level '] = pd.cut(df3["Level "],bins,labels = group_names)

In [15]:
df3.head(5)

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,High,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,High,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,High,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",High,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Low,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [16]:
df3['Level '] = df3['Level '].map({'Low': 1, 'Moderate': 2, 'High': 3}).astype(int)

In [17]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,3,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,3,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,3,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",3,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,1,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [18]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smoteon_autoencoding_features/fasttext_2autoencode_withstopwordchangelevels_20_features.csv"
df2 = pd.read_csv(path)
df2.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
0,0,0.018019,-0.029538,-0.055239,0.049131,0.042634,-0.055844,-0.013113,-0.028185,0.063799,...,0.042719,-0.024424,0.021971,-0.031706,0.045135,-0.046555,-0.059222,-0.004283,-0.001129,-0.056292
1,1,-0.030832,-0.042466,0.014082,0.039814,0.049848,-0.004768,-0.033239,0.011525,-0.005728,...,-0.040244,-0.024236,0.005437,-0.035944,-0.050629,-0.032357,-0.025965,-0.021170,0.011179,0.008437
2,2,-0.007108,-0.018637,-0.028971,0.021180,0.015200,-0.022956,-0.030151,0.022720,-0.003780,...,0.020665,-0.031942,0.012797,-0.034789,-0.003919,-0.047922,0.044918,0.033416,-0.013371,0.038272
3,3,-0.042697,0.001645,0.036530,0.051700,0.055478,0.056080,-0.019043,-0.031062,-0.011803,...,-0.047197,0.057927,-0.036228,0.050132,0.057844,-0.019156,0.009239,-0.006890,-0.030865,0.004539
4,4,-0.060208,0.016306,-0.007716,0.050473,-0.017961,0.019145,-0.030577,-0.031559,-0.037713,...,-0.006990,-0.049243,0.024274,-0.014497,-0.019525,0.019573,0.033455,-0.015994,-0.017160,0.016144

In [19]:
df2.drop(df2.columns[[0]], axis=1, inplace=True)
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.018019,-0.029538,-0.055239,0.049131,0.042634,-0.055844,-0.013113,-0.028185,0.063799,-0.032372,0.042719,-0.024424,0.021971,-0.031706,0.045135,-0.046555,-0.059222,-0.004283,-0.001129,-0.056292
1,-0.030832,-0.042466,0.014082,0.039814,0.049848,-0.004768,-0.033239,0.011525,-0.005728,0.018363,-0.040244,-0.024236,0.005437,-0.035944,-0.050629,-0.032357,-0.025965,-0.021170,0.011179,0.008437
2,-0.007108,-0.018637,-0.028971,0.021180,0.015200,-0.022956,-0.030151,0.022720,-0.003780,0.021422,0.020665,-0.031942,0.012797,-0.034789,-0.003919,-0.047922,0.044918,0.033416,-0.013371,0.038272
3,-0.042697,0.001645,0.036530,0.051700,0.055478,0.056080,-0.019043,-0.031062,-0.011803,0.004662,-0.047197,0.057927,-0.036228,0.050132,0.057844,-0.019156,0.009239,-0.006890,-0.030865,0.004539
4,-0.060208,0.016306,-0.007716,0.050473,-0.017961,0.019145,-0.030577,-0.031559,-0.037713,0.015892,-0.006990,-0.049243,0.024274,-0.014497,-0.019525,0.019573,0.033455,-0.015994,-0.017160,0.016144

In [20]:
df2['Level'] = df3['Level '].values
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,Level
0,0.018019,-0.029538,-0.055239,0.049131,0.042634,-0.055844,-0.013113,-0.028185,0.063799,-0.032372,...,-0.024424,0.021971,-0.031706,0.045135,-0.046555,-0.059222,-0.004283,-0.001129,-0.056292,3
1,-0.030832,-0.042466,0.014082,0.039814,0.049848,-0.004768,-0.033239,0.011525,-0.005728,0.018363,...,-0.024236,0.005437,-0.035944,-0.050629,-0.032357,-0.025965,-0.021170,0.011179,0.008437,3
2,-0.007108,-0.018637,-0.028971,0.021180,0.015200,-0.022956,-0.030151,0.022720,-0.003780,0.021422,...,-0.031942,0.012797,-0.034789,-0.003919,-0.047922,0.044918,0.033416,-0.013371,0.038272,3
3,-0.042697,0.001645,0.036530,0.051700,0.055478,0.056080,-0.019043,-0.031062,-0.011803,0.004662,...,0.057927,-0.036228,0.050132,0.057844,-0.019156,0.009239,-0.006890,-0.030865,0.004539,3
4,-0.060208,0.016306,-0.007716,0.050473,-0.017961,0.019145,-0.030577,-0.031559,-0.037713,0.015892,...,-0.049243,0.024274,-0.014497,-0.019525,0.019573,0.033455,-0.015994,-0.017160,0.016144,1

In [21]:
 #Data Shuffling
df2 = df2.sample(frac = 1) #frac denotes the fraction of samples to be returned. 

 
#train-test split
trdata = df2.sample(frac=0.7, random_state=25) #Training data = 70%
tsdata = df2.drop(trdata.index) #Testing data = 30%
X_train = trdata.iloc[:,:-1]
y_train = trdata.iloc[:,-1]
X_test = tsdata.iloc[:,:-1]
y_test = tsdata.iloc[:,-1]

#SMOTE
sm = SMOTE()
X_train, y_train = sm.fit_resample(X_train, y_train.ravel())

In [22]:

  #Model Calling
  Decision_tree_classifier(X_train, y_train, X_test, y_test)
  GNB_classifier(X_train, y_train, X_test, y_test)
  KNN_classifier(X_train, y_train, X_test, y_test) 
  svm_classifier(X_train, y_train, X_test, y_test)
  random_forest_classifier(X_train, y_train, X_test, y_test)
  ada_boost_classifier(X_train, y_train, X_test, y_test)
  gradient_boost_classifier(X_train, y_train, X_test, y_test)
  perceptron_classifier(X_train, y_train, X_test, y_test)

Decision Tree Accuracy: 0.3479923518164436
Decision Tree F1 Score: 0.3542139924152174
Gaussian Naive Bayes Accuracy: 0.32504780114722753
Gaussian Naive Bayes F1 Score: 0.3375846473194793
KNN Accuracy: 0.3479923518164436
KNN F1 Score: 0.34725124627691467
SVM Accuracy: 0.29636711281070743
SVM F1 Score: 0.2988040360369437
RF Accuracy: 0.3862332695984704
RF F1 Score: 0.3783848852734225
Ada-Boost Accuracy: 0.3422562141491396
Ada-Boost F1 Score: 0.3527965794897464
Gradient-Boost Accuracy: 0.32122370936902483
Gradient-Boost F1 Score: 0.328821073070518
Perceptron F1 score: 0.42469879518072284