Smote_tfidf_autoencoding_features

In [ ]:
from google.colab import drive
from google.colab import files

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd 
import numpy as np 
from imblearn.over_sampling import SMOTE 
from sklearn.model_selection import KFold
from sklearn import metrics
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.preprocessing import MultiLabelBinarizer

**Models**

In [3]:
def Decision_tree_classifier(X_train, y_train, X_test, y_test):
  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(class_weight = "balanced")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("Decision Tree Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Decision Tree F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [4]:
def GNB_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  gnb = GaussianNB()

  #Train the model using the training sets
  gnb.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = gnb.predict(X_test)

  print("Gaussian Naive Bayes Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gaussian Naive Bayes F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [5]:
def KNN_classifier (X_train, y_train, X_test, y_test):
  #Create KNN Classifier
  knn = KNeighborsClassifier(n_neighbors=5)

  #Train the model using the training sets
  knn.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = knn.predict(X_test)

  print("KNN Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("KNN F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [6]:
def svm_classifier (X_train, y_train, X_test, y_test):
  #Create a Support Vector Machine Classifier
  clf = svm.SVC(kernel='linear', class_weight = "balanced") # Linear Kernel

  #Train the model using the training sets
  clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("SVM Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("SVM F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [7]:
def random_forest_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  clf=RandomForestClassifier(n_estimators=100, class_weight = "balanced")

  #Train the model using the training sets y_pred=clf.predict(X_test)
  clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred=clf.predict(X_test)
  print("RF Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("RF F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [8]:
def ada_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  abc = AdaBoostClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = abc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Ada-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Ada-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [9]:
def gradient_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  gbc = GradientBoostingClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = gbc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Gradient-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gradient-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [10]:
def perceptron_classifier (X_train, y_train, X_test, y_test):
  p = Perceptron(random_state=150)
  p.fit(X_train, y_train)
  predictions_train = p.predict(X_train)
  predictions_test = p.predict(X_test)
  train_score = accuracy_score(predictions_train, y_train)
  #print("score on train data: ", train_score)
  test_score = f1_score(predictions_test, y_test, average='weighted' )
  print("Perceptron F1 score:", test_score)

In [11]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smoteon_autoencoding_features/data.csv"
df3 = pd.read_csv(path)
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,Level 5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,Level 5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,Level 5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",Level 5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Level 2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [12]:
df3.iloc[:,1].replace(['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'],
                        [1, 2, 3, 4, 5], inplace=True)

In [13]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [14]:
#define bins
bins = [0,2,4,5]
#name of the group 
group_names = ['Low', 'Moderate', 'High']
df3['Level '] = pd.cut(df3["Level "],bins,labels = group_names)

In [15]:
df3.head(5)

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,High,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,High,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,High,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",High,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Low,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [16]:
df3['Level '] = df3['Level '].map({'Low': 1, 'Moderate': 2, 'High': 3}).astype(int)

In [17]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,3,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,3,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,3,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",3,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,1,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [18]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smoteon_autoencoding_features/tfidf_2autoencode_withstopwordchangelevels_20_features.csv"
df2 = pd.read_csv(path)
df2.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
0,0,0.024491,-0.016143,0.009403,-0.038202,0.045519,-0.032752,0.018270,-0.011518,-0.008610,...,0.002963,0.042562,-0.008123,-0.031473,-0.009080,0.016978,-0.005193,-0.024720,0.013811,0.041464
1,1,-0.028000,0.016008,-0.052307,-0.050315,-0.014607,0.040440,0.032949,-0.009648,-0.048885,...,0.035351,0.025425,0.028788,-0.063036,-0.020060,0.045927,0.000586,-0.047134,0.003474,-0.041898
2,2,-0.055535,0.029058,0.000450,-0.035936,0.012763,0.042501,0.023011,0.007046,0.031442,...,0.048759,-0.037616,-0.001438,-0.023432,0.059181,0.025319,-0.002322,-0.001717,0.019474,-0.049398
3,3,-0.041542,-0.007725,0.037094,-0.056550,0.039651,-0.037678,-0.004004,0.059787,0.003576,...,0.051215,-0.034003,-0.038500,0.049039,0.017030,0.012583,-0.048766,-0.027923,0.055761,-0.049178
4,4,-0.047904,0.004081,0.030327,0.021185,0.022249,0.044669,-0.046751,0.023145,-0.005052,...,0.060730,0.008289,0.043693,-0.058434,-0.018971,-0.010360,-0.052328,0.039276,0.028463,0.058594

In [19]:
df2.drop(df2.columns[[0]], axis=1, inplace=True)
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.024491,-0.016143,0.009403,-0.038202,0.045519,-0.032752,0.018270,-0.011518,-0.008610,0.016378,0.002963,0.042562,-0.008123,-0.031473,-0.009080,0.016978,-0.005193,-0.024720,0.013811,0.041464
1,-0.028000,0.016008,-0.052307,-0.050315,-0.014607,0.040440,0.032949,-0.009648,-0.048885,-0.001897,0.035351,0.025425,0.028788,-0.063036,-0.020060,0.045927,0.000586,-0.047134,0.003474,-0.041898
2,-0.055535,0.029058,0.000450,-0.035936,0.012763,0.042501,0.023011,0.007046,0.031442,-0.064209,0.048759,-0.037616,-0.001438,-0.023432,0.059181,0.025319,-0.002322,-0.001717,0.019474,-0.049398
3,-0.041542,-0.007725,0.037094,-0.056550,0.039651,-0.037678,-0.004004,0.059787,0.003576,0.039354,0.051215,-0.034003,-0.038500,0.049039,0.017030,0.012583,-0.048766,-0.027923,0.055761,-0.049178
4,-0.047904,0.004081,0.030327,0.021185,0.022249,0.044669,-0.046751,0.023145,-0.005052,-0.018380,0.060730,0.008289,0.043693,-0.058434,-0.018971,-0.010360,-0.052328,0.039276,0.028463,0.058594

In [20]:
df2['Level'] = df3['Level '].values
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,Level
0,0.024491,-0.016143,0.009403,-0.038202,0.045519,-0.032752,0.018270,-0.011518,-0.008610,0.016378,...,0.042562,-0.008123,-0.031473,-0.009080,0.016978,-0.005193,-0.024720,0.013811,0.041464,3
1,-0.028000,0.016008,-0.052307,-0.050315,-0.014607,0.040440,0.032949,-0.009648,-0.048885,-0.001897,...,0.025425,0.028788,-0.063036,-0.020060,0.045927,0.000586,-0.047134,0.003474,-0.041898,3
2,-0.055535,0.029058,0.000450,-0.035936,0.012763,0.042501,0.023011,0.007046,0.031442,-0.064209,...,-0.037616,-0.001438,-0.023432,0.059181,0.025319,-0.002322,-0.001717,0.019474,-0.049398,3
3,-0.041542,-0.007725,0.037094,-0.056550,0.039651,-0.037678,-0.004004,0.059787,0.003576,0.039354,...,-0.034003,-0.038500,0.049039,0.017030,0.012583,-0.048766,-0.027923,0.055761,-0.049178,3
4,-0.047904,0.004081,0.030327,0.021185,0.022249,0.044669,-0.046751,0.023145,-0.005052,-0.018380,...,0.008289,0.043693,-0.058434,-0.018971,-0.010360,-0.052328,0.039276,0.028463,0.058594,1

In [21]:
 #Data Shuffling
df2 = df2.sample(frac = 1) #frac denotes the fraction of samples to be returned. 

 
#train-test split
trdata = df2.sample(frac=0.7, random_state=25) #Training data = 70%
tsdata = df2.drop(trdata.index) #Testing data = 30%
X_train = trdata.iloc[:,:-1]
y_train = trdata.iloc[:,-1]
X_test = tsdata.iloc[:,:-1]
y_test = tsdata.iloc[:,-1]

#SMOTE
sm = SMOTE()
X_train, y_train = sm.fit_resample(X_train, y_train.ravel())

In [22]:

  #Model Calling
  Decision_tree_classifier(X_train, y_train, X_test, y_test)
  GNB_classifier(X_train, y_train, X_test, y_test)
  KNN_classifier(X_train, y_train, X_test, y_test) 
  svm_classifier(X_train, y_train, X_test, y_test)
  random_forest_classifier(X_train, y_train, X_test, y_test)
  ada_boost_classifier(X_train, y_train, X_test, y_test)
  gradient_boost_classifier(X_train, y_train, X_test, y_test)
  perceptron_classifier(X_train, y_train, X_test, y_test)

Decision Tree Accuracy: 0.38049713193116635
Decision Tree F1 Score: 0.3889905448185092
Gaussian Naive Bayes Accuracy: 0.372848948374761
Gaussian Naive Bayes F1 Score: 0.38328812366100096
KNN Accuracy: 0.3384321223709369
KNN F1 Score: 0.33598139674424615
SVM Accuracy: 0.35181644359464626
SVM F1 Score: 0.3614401292283011
RF Accuracy: 0.4149139579349904
RF F1 Score: 0.41136852004554336
Ada-Boost Accuracy: 0.34990439770554493
Ada-Boost F1 Score: 0.36181385544711636
Gradient-Boost Accuracy: 0.3632887189292543
Gradient-Boost F1 Score: 0.369321718003004
Perceptron F1 score: 0.42825983861917627