Smote_bert_autoencoding_features

In [ ]:
from google.colab import drive
from google.colab import files

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd 
import numpy as np 
from imblearn.over_sampling import SMOTE 
from sklearn.model_selection import KFold 
from sklearn import metrics
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.preprocessing import MultiLabelBinarizer

**Models**

In [3]:
def Decision_tree_classifier(X_train, y_train, X_test, y_test):
  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(class_weight = "balanced")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("Decision Tree Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Decision Tree F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [4]:
def GNB_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  gnb = GaussianNB()

  #Train the model using the training sets
  gnb.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = gnb.predict(X_test)

  print("Gaussian Naive Bayes Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gaussian Naive Bayes F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [5]:
def KNN_classifier (X_train, y_train, X_test, y_test):
  #Create KNN Classifier
  knn = KNeighborsClassifier(n_neighbors=5)

  #Train the model using the training sets
  knn.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = knn.predict(X_test)

  print("KNN Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("KNN F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [6]:
def svm_classifier (X_train, y_train, X_test, y_test):
  #Create a Support Vector Machine Classifier
  clf = svm.SVC(kernel='linear', class_weight = "balanced") # Linear Kernel

  #Train the model using the training sets
  clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("SVM Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("SVM F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [7]:
def random_forest_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  clf=RandomForestClassifier(n_estimators=100, class_weight = "balanced")

  #Train the model using the training sets y_pred=clf.predict(X_test)
  clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred=clf.predict(X_test)
  print("RF Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("RF F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [8]:
def ada_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  abc = AdaBoostClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = abc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Ada-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Ada-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [9]:
def gradient_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  gbc = GradientBoostingClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = gbc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Gradient-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gradient-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [10]:
def perceptron_classifier (X_train, y_train, X_test, y_test):
  p = Perceptron(random_state=150)
  p.fit(X_train, y_train)
  predictions_train = p.predict(X_train)
  predictions_test = p.predict(X_test)
  train_score = accuracy_score(predictions_train, y_train)
  #print("score on train data: ", train_score)
  test_score = f1_score(predictions_test, y_test, average='weighted' )
  print("Perceptron F1 score:", test_score)

In [11]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smoteon_autoencoding_features/data.csv"
df3 = pd.read_csv(path)
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,Level 5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,Level 5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,Level 5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",Level 5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Level 2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [12]:
df3.iloc[:,1].replace(['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'],
                        [1, 2, 3, 4, 5], inplace=True)

In [13]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [14]:
#define bins
bins = [0,2,4,5]
#name of the group 
group_names = ['Low', 'Moderate', 'High']
df3['Level '] = pd.cut(df3["Level "],bins,labels = group_names)

In [15]:
df3.head(5)

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,High,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,High,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,High,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",High,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Low,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [16]:
df3['Level '] = df3['Level '].map({'Low': 1, 'Moderate': 2, 'High': 3}).astype(int)

In [17]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,3,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,3,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,3,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",3,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,1,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [18]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smoteon_autoencoding_features/bert_2autoencode_withstopwordchangelevels_20_features.csv"
df2 = pd.read_csv(path)
df2.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
0,0,-0.040766,-0.011165,0.049619,-0.036195,-0.001590,-0.036157,-0.055003,-0.058027,0.003974,...,0.042667,-0.032662,-0.015013,-0.060094,-0.013859,-0.025651,0.023544,0.014834,0.036700,0.008345
1,1,0.034262,0.044011,0.049394,0.044758,0.021972,-0.010830,0.021829,-0.051042,-0.027442,...,-0.024802,0.053512,0.013984,-0.013991,0.042056,-0.046459,0.024926,0.019973,-0.003224,-0.020229
2,2,0.030641,0.043326,0.018746,0.046257,-0.005205,0.046819,-0.032563,0.034202,-0.012302,...,-0.020946,-0.061394,-0.001178,-0.062170,-0.050622,0.038123,-0.011258,-0.013091,0.007666,0.017925
3,3,0.039085,0.026694,0.036269,0.004421,-0.020205,0.010260,-0.031908,-0.034599,-0.046219,...,0.000350,-0.001665,-0.015767,-0.011137,0.042106,-0.047777,0.032661,-0.016617,0.046089,0.000738
4,4,0.052076,0.061837,-0.030563,-0.049211,0.019215,-0.017553,-0.051692,0.044288,0.009463,...,-0.007853,-0.050963,-0.022250,-0.009415,-0.043066,0.035982,0.049873,0.014536,0.029244,0.031482

In [19]:
df2.drop(df2.columns[[0]], axis=1, inplace=True)
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,-0.040766,-0.011165,0.049619,-0.036195,-0.001590,-0.036157,-0.055003,-0.058027,0.003974,0.051038,0.042667,-0.032662,-0.015013,-0.060094,-0.013859,-0.025651,0.023544,0.014834,0.036700,0.008345
1,0.034262,0.044011,0.049394,0.044758,0.021972,-0.010830,0.021829,-0.051042,-0.027442,-0.034877,-0.024802,0.053512,0.013984,-0.013991,0.042056,-0.046459,0.024926,0.019973,-0.003224,-0.020229
2,0.030641,0.043326,0.018746,0.046257,-0.005205,0.046819,-0.032563,0.034202,-0.012302,-0.048479,-0.020946,-0.061394,-0.001178,-0.062170,-0.050622,0.038123,-0.011258,-0.013091,0.007666,0.017925
3,0.039085,0.026694,0.036269,0.004421,-0.020205,0.010260,-0.031908,-0.034599,-0.046219,-0.028736,0.000350,-0.001665,-0.015767,-0.011137,0.042106,-0.047777,0.032661,-0.016617,0.046089,0.000738
4,0.052076,0.061837,-0.030563,-0.049211,0.019215,-0.017553,-0.051692,0.044288,0.009463,-0.008369,-0.007853,-0.050963,-0.022250,-0.009415,-0.043066,0.035982,0.049873,0.014536,0.029244,0.031482

In [20]:
df2['Level'] = df3['Level '].values
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,Level
0,-0.040766,-0.011165,0.049619,-0.036195,-0.001590,-0.036157,-0.055003,-0.058027,0.003974,0.051038,...,-0.032662,-0.015013,-0.060094,-0.013859,-0.025651,0.023544,0.014834,0.036700,0.008345,3
1,0.034262,0.044011,0.049394,0.044758,0.021972,-0.010830,0.021829,-0.051042,-0.027442,-0.034877,...,0.053512,0.013984,-0.013991,0.042056,-0.046459,0.024926,0.019973,-0.003224,-0.020229,3
2,0.030641,0.043326,0.018746,0.046257,-0.005205,0.046819,-0.032563,0.034202,-0.012302,-0.048479,...,-0.061394,-0.001178,-0.062170,-0.050622,0.038123,-0.011258,-0.013091,0.007666,0.017925,3
3,0.039085,0.026694,0.036269,0.004421,-0.020205,0.010260,-0.031908,-0.034599,-0.046219,-0.028736,...,-0.001665,-0.015767,-0.011137,0.042106,-0.047777,0.032661,-0.016617,0.046089,0.000738,3
4,0.052076,0.061837,-0.030563,-0.049211,0.019215,-0.017553,-0.051692,0.044288,0.009463,-0.008369,...,-0.050963,-0.022250,-0.009415,-0.043066,0.035982,0.049873,0.014536,0.029244,0.031482,1

In [21]:
 #Data Shuffling
df2 = df2.sample(frac = 1) #frac denotes the fraction of samples to be returned. 

 
#train-test split
trdata = df2.sample(frac=0.7, random_state=25) #Training data = 70%
tsdata = df2.drop(trdata.index) #Testing data = 30%
X_train = trdata.iloc[:,:-1]
y_train = trdata.iloc[:,-1]
X_test = tsdata.iloc[:,:-1]
y_test = tsdata.iloc[:,-1]

#SMOTE
sm = SMOTE()
X_train, y_train = sm.fit_resample(X_train, y_train.ravel())

In [22]:

  #Model Calling
  Decision_tree_classifier(X_train, y_train, X_test, y_test)
  GNB_classifier(X_train, y_train, X_test, y_test)
  KNN_classifier(X_train, y_train, X_test, y_test) 
  svm_classifier(X_train, y_train, X_test, y_test)
  random_forest_classifier(X_train, y_train, X_test, y_test)
  ada_boost_classifier(X_train, y_train, X_test, y_test)
  gradient_boost_classifier(X_train, y_train, X_test, y_test)
  perceptron_classifier(X_train, y_train, X_test, y_test)

Decision Tree Accuracy: 0.33078393881453155
Decision Tree F1 Score: 0.33166659254623915
Gaussian Naive Bayes Accuracy: 0.35564053537284895
Gaussian Naive Bayes F1 Score: 0.3554105459734765
KNN Accuracy: 0.3441682600382409
KNN F1 Score: 0.3363188779279029
SVM Accuracy: 0.3690248565965583
SVM F1 Score: 0.370649234874924
RF Accuracy: 0.3652007648183556
RF F1 Score: 0.3514146761188148
Ada-Boost Accuracy: 0.32887189292543023
Ada-Boost F1 Score: 0.33176110142083226
Gradient-Boost Accuracy: 0.32695984703632885
Gradient-Boost F1 Score: 0.3217391173037717
Perceptron F1 score: 0.6127320954907162