Smote_pca_features

In [ ]:
from google.colab import drive
from google.colab import files

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd 
import numpy as np 
from imblearn.over_sampling import SMOTE 
from sklearn.model_selection import KFold
from sklearn import metrics
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.preprocessing import MultiLabelBinarizer

**Models**

In [3]:
def Decision_tree_classifier(X_train, y_train, X_test, y_test):
  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(class_weight = "balanced")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("Decision Tree Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Decision Tree F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [4]:
def GNB_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  gnb = GaussianNB()

  #Train the model using the training sets
  gnb.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = gnb.predict(X_test)

  print("Gaussian Naive Bayes Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gaussian Naive Bayes F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [5]:
def KNN_classifier (X_train, y_train, X_test, y_test):
  #Create KNN Classifier
  knn = KNeighborsClassifier(n_neighbors=5)

  #Train the model using the training sets
  knn.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = knn.predict(X_test)

  print("KNN Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("KNN F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [6]:
def svm_classifier (X_train, y_train, X_test, y_test):
  #Create a Support Vector Machine Classifier
  clf = svm.SVC(kernel='linear', class_weight = "balanced") # Linear Kernel

  #Train the model using the training sets
  clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("SVM Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("SVM F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [7]:
def random_forest_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  clf=RandomForestClassifier(n_estimators=100, class_weight = "balanced")

  #Train the model using the training sets y_pred=clf.predict(X_test)
  clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred=clf.predict(X_test)
  print("RF Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("RF F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [8]:
def ada_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  abc = AdaBoostClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = abc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Ada-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Ada-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [9]:
def gradient_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  gbc = GradientBoostingClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = gbc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Gradient-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gradient-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [10]:
def perceptron_classifier (X_train, y_train, X_test, y_test):
  p = Perceptron(random_state=150)
  p.fit(X_train, y_train)
  predictions_train = p.predict(X_train)
  predictions_test = p.predict(X_test)
  train_score = accuracy_score(predictions_train, y_train)
  #print("score on train data: ", train_score)
  test_score = f1_score(predictions_test, y_test, average='weighted' )
  print("Perceptron F1 score:", test_score)

In [11]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smote_pca_fasttext/data.csv"
df3 = pd.read_csv(path)
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,Level 5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,Level 5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,Level 5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",Level 5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Level 2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [12]:
df3.iloc[:,1].replace(['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'],
                        [1, 2, 3, 4, 5], inplace=True)

In [13]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [14]:
#define bins
bins = [0,2,4,5]
#name of the group 
group_names = ['Low', 'Moderate', 'High']
df3['Level '] = pd.cut(df3["Level "],bins,labels = group_names)

In [15]:
df3.head(5)

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,High,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,High,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,High,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",High,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Low,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [16]:
df3['Level '] = df3['Level '].map({'Low': 1, 'Moderate': 2, 'High': 3}).astype(int)

In [17]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,3,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,3,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,3,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",3,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,1,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [18]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smote_pca_fasttext/fasttext_withstopwordchangelevels_250_features.csv"
df2 = pd.read_csv(path)
df2.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,240,241,242,243,244,245,246,247,248,249
0,0,3.346298,-5.855203,0.545569,-4.081459,-0.838505,-2.760930,-3.665564,-4.701012,-0.379222,...,-7.637054e-08,-6.715349e-08,1.107110e-07,2.082561e-07,1.062625e-07,4.672368e-07,6.688171e-08,3.442251e-07,-8.716242e-09,1.211639e-07
1,1,9.310650,10.553516,-0.420077,-2.689325,1.762551,-3.791009,5.668473,4.540495,4.148841,...,-3.189717e-07,-3.471711e-07,-4.298393e-07,1.966374e-07,1.942686e-07,-1.092340e-07,3.843313e-08,-3.668053e-08,-4.159583e-07,2.714960e-07
2,2,7.220743,-10.091701,-5.013541,5.737518,-4.572323,-0.763304,5.369118,0.316245,2.031913,...,4.071273e-07,-2.161027e-07,-1.232943e-08,3.417658e-07,-4.717671e-07,2.435786e-07,3.461771e-08,-1.892858e-07,5.259804e-08,-2.445886e-07
3,3,-6.708870,-0.637191,-4.688200,-0.309604,-0.462299,-3.399458,0.898308,1.732282,0.490729,...,-1.448756e-07,1.176835e-07,1.247300e-07,2.171227e-07,1.289535e-08,-1.066788e-07,-1.421309e-07,1.254054e-08,-8.528553e-08,2.997065e-07
4,4,7.375775,15.082849,8.790871,0.505721,2.386350,-12.606893,0.937749,-10.020070,-2.543565,...,1.585627e-07,-3.842735e-08,-1.373187e-07,-1.846871e-07,2.227049e-08,-1.518292e-07,2.119794e-08,1.547541e-07,-7.779088e-08,1.955483e-07

In [19]:
df2.drop(df2.columns[[0]], axis=1, inplace=True)
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,240,241,242,243,244,245,246,247,248,249
0,3.346298,-5.855203,0.545569,-4.081459,-0.838505,-2.760930,-3.665564,-4.701012,-0.379222,2.062488,...,-7.637054e-08,-6.715349e-08,1.107110e-07,2.082561e-07,1.062625e-07,4.672368e-07,6.688171e-08,3.442251e-07,-8.716242e-09,1.211639e-07
1,9.310650,10.553516,-0.420077,-2.689325,1.762551,-3.791009,5.668473,4.540495,4.148841,-4.707219,...,-3.189717e-07,-3.471711e-07,-4.298393e-07,1.966374e-07,1.942686e-07,-1.092340e-07,3.843313e-08,-3.668053e-08,-4.159583e-07,2.714960e-07
2,7.220743,-10.091701,-5.013541,5.737518,-4.572323,-0.763304,5.369118,0.316245,2.031913,6.149280,...,4.071273e-07,-2.161027e-07,-1.232943e-08,3.417658e-07,-4.717671e-07,2.435786e-07,3.461771e-08,-1.892858e-07,5.259804e-08,-2.445886e-07
3,-6.708870,-0.637191,-4.688200,-0.309604,-0.462299,-3.399458,0.898308,1.732282,0.490729,1.743079,...,-1.448756e-07,1.176835e-07,1.247300e-07,2.171227e-07,1.289535e-08,-1.066788e-07,-1.421309e-07,1.254054e-08,-8.528553e-08,2.997065e-07
4,7.375775,15.082849,8.790871,0.505721,2.386350,-12.606893,0.937749,-10.020070,-2.543565,5.638123,...,1.585627e-07,-3.842735e-08,-1.373187e-07,-1.846871e-07,2.227049e-08,-1.518292e-07,2.119794e-08,1.547541e-07,-7.779088e-08,1.955483e-07

In [20]:
df2['Level'] = df3['Level '].values
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,241,242,243,244,245,246,247,248,249,Level
0,3.346298,-5.855203,0.545569,-4.081459,-0.838505,-2.760930,-3.665564,-4.701012,-0.379222,2.062488,...,-6.715349e-08,1.107110e-07,2.082561e-07,1.062625e-07,4.672368e-07,6.688171e-08,3.442251e-07,-8.716242e-09,1.211639e-07,3
1,9.310650,10.553516,-0.420077,-2.689325,1.762551,-3.791009,5.668473,4.540495,4.148841,-4.707219,...,-3.471711e-07,-4.298393e-07,1.966374e-07,1.942686e-07,-1.092340e-07,3.843313e-08,-3.668053e-08,-4.159583e-07,2.714960e-07,3
2,7.220743,-10.091701,-5.013541,5.737518,-4.572323,-0.763304,5.369118,0.316245,2.031913,6.149280,...,-2.161027e-07,-1.232943e-08,3.417658e-07,-4.717671e-07,2.435786e-07,3.461771e-08,-1.892858e-07,5.259804e-08,-2.445886e-07,3
3,-6.708870,-0.637191,-4.688200,-0.309604,-0.462299,-3.399458,0.898308,1.732282,0.490729,1.743079,...,1.176835e-07,1.247300e-07,2.171227e-07,1.289535e-08,-1.066788e-07,-1.421309e-07,1.254054e-08,-8.528553e-08,2.997065e-07,3
4,7.375775,15.082849,8.790871,0.505721,2.386350,-12.606893,0.937749,-10.020070,-2.543565,5.638123,...,-3.842735e-08,-1.373187e-07,-1.846871e-07,2.227049e-08,-1.518292e-07,2.119794e-08,1.547541e-07,-7.779088e-08,1.955483e-07,1

In [21]:
 #Data Shuffling
df2 = df2.sample(frac = 1) #frac denotes the fraction of samples to be returned. 

 
#train-test split
trdata = df2.sample(frac=0.7, random_state=25) #Training data = 70%
tsdata = df2.drop(trdata.index) #Testing data = 30%
X_train = trdata.iloc[:,:-1]
y_train = trdata.iloc[:,-1]
X_test = tsdata.iloc[:,:-1]
y_test = tsdata.iloc[:,-1]

#SMOTE
sm = SMOTE()
X_train, y_train = sm.fit_resample(X_train, y_train.ravel())

In [22]:

  #Model Calling
  Decision_tree_classifier(X_train, y_train, X_test, y_test)
  GNB_classifier(X_train, y_train, X_test, y_test)
  KNN_classifier(X_train, y_train, X_test, y_test) 
  svm_classifier(X_train, y_train, X_test, y_test)
  random_forest_classifier(X_train, y_train, X_test, y_test)
  ada_boost_classifier(X_train, y_train, X_test, y_test)
  gradient_boost_classifier(X_train, y_train, X_test, y_test)
  perceptron_classifier(X_train, y_train, X_test, y_test)

Decision Tree Accuracy: 0.3384321223709369
Decision Tree F1 Score: 0.3414775427553549
Gaussian Naive Bayes Accuracy: 0.32887189292543023
Gaussian Naive Bayes F1 Score: 0.3196615317856369
KNN Accuracy: 0.35564053537284895
KNN F1 Score: 0.3515679882585263
SVM Accuracy: 0.32887189292543023
SVM F1 Score: 0.3270088164564877
RF Accuracy: 0.35564053537284895
RF F1 Score: 0.3347203050934984
Ada-Boost Accuracy: 0.361376673040153
Ada-Boost F1 Score: 0.36399243950118615
Gradient-Boost Accuracy: 0.37667304015296366
Gradient-Boost F1 Score: 0.3762040822814431
Perceptron F1 score: 0.2901674339189461