Smote_pca_features

In [ ]:
from google.colab import drive
from google.colab import files

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd 
import numpy as np 
from imblearn.over_sampling import SMOTE 
from sklearn.model_selection import KFold
from sklearn import metrics 
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.preprocessing import MultiLabelBinarizer

**Models**

In [3]:
def Decision_tree_classifier(X_train, y_train, X_test, y_test):
  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(class_weight = "balanced")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("Decision Tree Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Decision Tree F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [4]:
def GNB_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  gnb = GaussianNB()

  #Train the model using the training sets
  gnb.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = gnb.predict(X_test)

  print("Gaussian Naive Bayes Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gaussian Naive Bayes F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [5]:
def KNN_classifier (X_train, y_train, X_test, y_test):
  #Create KNN Classifier
  knn = KNeighborsClassifier(n_neighbors=5)

  #Train the model using the training sets
  knn.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = knn.predict(X_test)

  print("KNN Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("KNN F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [7]:
def svm_classifier (X_train, y_train, X_test, y_test):
  #Create a Support Vector Machine Classifier
  clf = svm.SVC(kernel='linear', class_weight = "balanced") # Linear Kernel

  #Train the model using the training sets
  clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("SVM Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("SVM F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [8]:
def random_forest_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  clf=RandomForestClassifier(n_estimators=100, class_weight = "balanced")

  #Train the model using the training sets y_pred=clf.predict(X_test)
  clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred=clf.predict(X_test)
  print("RF Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("RF F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [9]:
def ada_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  abc = AdaBoostClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = abc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Ada-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Ada-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [10]:
def gradient_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  gbc = GradientBoostingClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = gbc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Gradient-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gradient-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [11]:
def perceptron_classifier (X_train, y_train, X_test, y_test):
  p = Perceptron(random_state=150)
  p.fit(X_train, y_train)
  predictions_train = p.predict(X_train)
  predictions_test = p.predict(X_test)
  train_score = accuracy_score(predictions_train, y_train)
  #print("score on train data: ", train_score)
  test_score = f1_score(predictions_test, y_test, average='weighted' )
  print("Perceptron F1 score:", test_score)

In [12]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smote_pca_fasttext/data.csv"
df3 = pd.read_csv(path)
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,Level 5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,Level 5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,Level 5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",Level 5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Level 2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [13]:
df3.iloc[:,1].replace(['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'],
                        [1, 2, 3, 4, 5], inplace=True)

In [14]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [15]:
#define bins
bins = [0,2,4,5]
#name of the group 
group_names = ['Low', 'Moderate', 'High']
df3['Level '] = pd.cut(df3["Level "],bins,labels = group_names)

In [16]:
df3.head(5)

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,High,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,High,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,High,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",High,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Low,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [17]:
df3['Level '] = df3['Level '].map({'Low': 1, 'Moderate': 2, 'High': 3}).astype(int)

In [18]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,3,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,3,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,3,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",3,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,1,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [19]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smote_pca_fasttext/fasttext_200_features.csv"
df2 = pd.read_csv(path)
df2.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,190,191,192,193,194,195,196,197,198,199
0,0,-0.045237,9.044040,4.043429,-0.526291,4.656052,5.548668,5.437920,-1.693246,1.186458,...,-2.569138e-08,2.578294e-07,-1.437080e-07,2.467777e-07,-3.201949e-08,3.784236e-07,4.621108e-08,2.610936e-07,-2.626437e-07,2.089732e-07
1,1,-5.898010,0.930086,3.812281,0.067162,2.070109,-2.211751,0.428379,5.459890,-0.976669,...,7.596994e-08,-5.530957e-07,8.297208e-07,2.136562e-07,6.258647e-07,-3.021505e-07,-3.459305e-07,2.898783e-07,-2.646882e-07,-1.605603e-07
2,2,33.251688,1.650107,-5.504238,-0.846860,4.862974,3.138222,2.912264,-0.992158,-0.177087,...,-1.204792e-07,-4.781426e-07,-1.383552e-08,-2.911259e-07,1.436512e-07,3.382651e-07,1.290658e-07,-2.367844e-09,2.170180e-07,1.280895e-07
3,3,0.020924,6.274368,-5.278525,4.288215,-5.342193,3.618706,-2.397702,1.702414,1.248594,...,6.342539e-08,-1.075776e-07,6.993323e-08,5.808999e-08,-1.168847e-07,2.569486e-07,2.080729e-07,4.243144e-08,2.889872e-07,-8.601232e-08
4,4,-3.663867,2.086336,0.594946,-0.518693,-1.174088,0.505647,1.208072,-0.573444,3.545797,...,3.163747e-07,-5.678777e-07,-4.660615e-07,-1.429647e-07,1.234872e-07,6.541124e-08,4.474175e-07,5.436996e-07,1.486766e-07,-8.067471e-08

In [20]:
df2.drop(df2.columns[[0]], axis=1, inplace=True)
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
0,-0.045237,9.044040,4.043429,-0.526291,4.656052,5.548668,5.437920,-1.693246,1.186458,-2.728166,...,-2.569138e-08,2.578294e-07,-1.437080e-07,2.467777e-07,-3.201949e-08,3.784236e-07,4.621108e-08,2.610936e-07,-2.626437e-07,2.089732e-07
1,-5.898010,0.930086,3.812281,0.067162,2.070109,-2.211751,0.428379,5.459890,-0.976669,-1.920996,...,7.596994e-08,-5.530957e-07,8.297208e-07,2.136562e-07,6.258647e-07,-3.021505e-07,-3.459305e-07,2.898783e-07,-2.646882e-07,-1.605603e-07
2,33.251688,1.650107,-5.504238,-0.846860,4.862974,3.138222,2.912264,-0.992158,-0.177087,3.365038,...,-1.204792e-07,-4.781426e-07,-1.383552e-08,-2.911259e-07,1.436512e-07,3.382651e-07,1.290658e-07,-2.367844e-09,2.170180e-07,1.280895e-07
3,0.020924,6.274368,-5.278525,4.288215,-5.342193,3.618706,-2.397702,1.702414,1.248594,-1.705416,...,6.342539e-08,-1.075776e-07,6.993323e-08,5.808999e-08,-1.168847e-07,2.569486e-07,2.080729e-07,4.243144e-08,2.889872e-07,-8.601232e-08
4,-3.663867,2.086336,0.594946,-0.518693,-1.174088,0.505647,1.208072,-0.573444,3.545797,2.872104,...,3.163747e-07,-5.678777e-07,-4.660615e-07,-1.429647e-07,1.234872e-07,6.541124e-08,4.474175e-07,5.436996e-07,1.486766e-07,-8.067471e-08

In [21]:
df2['Level'] = df3['Level '].values
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,191,192,193,194,195,196,197,198,199,Level
0,-0.045237,9.044040,4.043429,-0.526291,4.656052,5.548668,5.437920,-1.693246,1.186458,-2.728166,...,2.578294e-07,-1.437080e-07,2.467777e-07,-3.201949e-08,3.784236e-07,4.621108e-08,2.610936e-07,-2.626437e-07,2.089732e-07,3
1,-5.898010,0.930086,3.812281,0.067162,2.070109,-2.211751,0.428379,5.459890,-0.976669,-1.920996,...,-5.530957e-07,8.297208e-07,2.136562e-07,6.258647e-07,-3.021505e-07,-3.459305e-07,2.898783e-07,-2.646882e-07,-1.605603e-07,3
2,33.251688,1.650107,-5.504238,-0.846860,4.862974,3.138222,2.912264,-0.992158,-0.177087,3.365038,...,-4.781426e-07,-1.383552e-08,-2.911259e-07,1.436512e-07,3.382651e-07,1.290658e-07,-2.367844e-09,2.170180e-07,1.280895e-07,3
3,0.020924,6.274368,-5.278525,4.288215,-5.342193,3.618706,-2.397702,1.702414,1.248594,-1.705416,...,-1.075776e-07,6.993323e-08,5.808999e-08,-1.168847e-07,2.569486e-07,2.080729e-07,4.243144e-08,2.889872e-07,-8.601232e-08,3
4,-3.663867,2.086336,0.594946,-0.518693,-1.174088,0.505647,1.208072,-0.573444,3.545797,2.872104,...,-5.678777e-07,-4.660615e-07,-1.429647e-07,1.234872e-07,6.541124e-08,4.474175e-07,5.436996e-07,1.486766e-07,-8.067471e-08,1

In [22]:
 #Data Shuffling
df2 = df2.sample(frac = 1) #frac denotes the fraction of samples to be returned. 

 
#train-test split
trdata = df2.sample(frac=0.7, random_state=25) #Training data = 70%
tsdata = df2.drop(trdata.index) #Testing data = 30%
X_train = trdata.iloc[:,:-1]
y_train = trdata.iloc[:,-1]
X_test = tsdata.iloc[:,:-1]
y_test = tsdata.iloc[:,-1]

#SMOTE
sm = SMOTE()
X_train, y_train = sm.fit_resample(X_train, y_train.ravel())

In [23]:

  #Model Calling
  Decision_tree_classifier(X_train, y_train, X_test, y_test)
  GNB_classifier(X_train, y_train, X_test, y_test)
  KNN_classifier(X_train, y_train, X_test, y_test) 
  svm_classifier(X_train, y_train, X_test, y_test)
  random_forest_classifier(X_train, y_train, X_test, y_test)
  ada_boost_classifier(X_train, y_train, X_test, y_test)
  gradient_boost_classifier(X_train, y_train, X_test, y_test)
  perceptron_classifier(X_train, y_train, X_test, y_test)

Decision Tree Accuracy: 0.3154875717017208
Decision Tree F1 Score: 0.3188710534703778
Gaussian Naive Bayes Accuracy: 0.2925430210325048
Gaussian Naive Bayes F1 Score: 0.27941018075943924
KNN Accuracy: 0.3135755258126195
KNN F1 Score: 0.3085227251225141
SVM Accuracy: 0.372848948374761
SVM F1 Score: 0.3744893325101508
RF Accuracy: 0.3938814531548757
RF F1 Score: 0.3772997926667901
Ada-Boost Accuracy: 0.35564053537284895
Ada-Boost F1 Score: 0.3604238045527599
Gradient-Boost Accuracy: 0.34990439770554493
Gradient-Boost F1 Score: 0.3498604415127623
Perceptron F1 score: 0.3327091238917517