In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest 
from sklearn.feature_selection import f_classif

In [32]:
df1 = pd.read_csv("/content/drive/MyDrive/newpro/threeclass_problem/FastText_levelsrecode.csv")
df2 = pd.read_csv("/content/drive/MyDrive/newpro/threeclass_problem/glove_levelsrecode.csv")
df3 =  pd.read_csv("/content/drive/MyDrive/newpro/threeclass_problem/w2v_levelsrecode.csv")
df4 =  pd.read_csv("/content/drive/MyDrive/newpro/threeclass_problem/bert_levelsrecode.csv")
df6 =  pd.read_csv("/content/drive/MyDrive/newpro/threeclass_problem/tfidf_levelsrecode.csv")
df5 =  pd.read_csv("/content/drive/MyDrive/newpro/threeclass_problem/data.csv")

In [33]:
df5.iloc[:,1].replace(['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'],
                        [1, 2, 3, 4, 5], inplace=True)

In [34]:
df5.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [35]:
#define bins
bins = [0,2,4,5]
#name of the group 
group_names = ['Low', 'Moderate', 'High']
df5['Level '] = pd.cut(df5["Level "],bins,labels = group_names)

In [36]:
df5.head(5)

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,High,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,High,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,High,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",High,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Low,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [37]:
df5['Level '] = df5['Level '].map({'Low': 1, 'Moderate': 2, 'High': 3}).astype(int)

In [38]:
df5.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,3,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,3,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,3,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",3,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,1,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [39]:
df1.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,290,291,292,293,294,295,296,297,298,299
0,0,-0.047231,0.015711,-0.071031,-0.007662,0.030991,0.059917,0.004687,-0.046487,0.107146,...,-0.018673,0.030429,-0.016143,0.046663,0.034890,0.028259,-0.000247,-0.030757,0.008817,-0.006377
1,1,-0.098719,0.015418,-0.097384,-0.038516,0.043484,0.060653,0.018721,-0.041094,0.129638,...,0.000181,0.017451,-0.012927,0.064079,0.031009,0.022566,0.020062,-0.025959,-0.026582,0.008801
2,2,-0.092993,0.026287,-0.107235,-0.050508,0.044317,0.051024,0.017439,-0.049028,0.143363,...,0.016668,0.016611,-0.022086,0.065026,0.024556,0.032230,-0.003800,-0.040938,-0.027009,0.004288
3,3,-0.074855,0.020305,-0.100434,-0.031188,0.016835,0.047498,-0.001790,-0.055538,0.132829,...,-0.001125,0.033835,-0.021322,0.058418,0.049020,0.035385,-0.014268,-0.031588,-0.023069,0.008638
4,4,-0.044288,0.022878,-0.035347,-0.002803,0.065113,0.079378,0.019056,-0.048419,0.116516,...,-0.013225,0.046087,-0.002287,0.054631,-0.005369,0.021631,0.013978,-0.053094,0.023938,0.000747

In [40]:
df2.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,290,291,292,293,294,295,296,297,298,299
0,0,-0.018407,0.085011,0.029703,-0.044558,-0.046228,0.002105,-0.017075,0.011753,0.039239,...,0.007392,-0.050867,-0.032619,-0.040177,0.003517,0.009812,0.033037,-0.059005,0.020749,0.040800
1,1,-0.061130,0.069028,0.029945,-0.075593,-0.055460,0.029755,-0.034010,0.027264,0.033029,...,0.003908,-0.056133,0.006894,0.011421,0.056875,0.074536,0.001674,-0.046282,-0.029717,-0.002265
2,2,-0.084698,0.059528,-0.019130,-0.054112,-0.039338,0.013001,-0.020171,0.000319,0.021646,...,-0.014100,-0.059806,0.025660,0.011339,0.019782,0.032892,0.005613,-0.029948,-0.029217,-0.031719
3,3,-0.049269,0.032437,-0.001154,-0.040035,-0.033356,0.029849,0.004792,0.000715,0.013032,...,-0.018463,-0.021215,0.019852,0.006229,0.031585,0.018694,0.036211,-0.089839,-0.007266,-0.009470
4,4,-0.090736,0.040478,0.054596,-0.015434,-0.090787,0.020753,0.070594,-0.048692,-0.019835,...,0.041861,-0.051594,0.042672,-0.065068,0.078107,0.028808,-0.011964,-0.095961,-0.040278,-0.061897

In [41]:
df3.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,290,291,292,293,294,295,296,297,298,299
0,0,-0.132192,0.085008,-0.021770,0.104603,-0.064176,0.014193,-0.075376,-0.062582,0.017596,...,0.057682,0.009523,-0.101325,0.114898,-0.016636,-0.134433,-0.144924,-0.050143,-0.100066,0.150123
1,1,-0.169962,0.117862,-0.023319,0.127086,-0.067426,0.011222,-0.069913,-0.051933,-0.023587,...,0.068842,-0.015122,-0.104072,0.097132,-0.028843,-0.158527,-0.118772,-0.044826,-0.101228,0.156272
2,2,-0.178082,0.116493,0.005438,0.142175,-0.040640,0.008901,-0.113469,-0.031516,-0.040196,...,0.087883,-0.034578,-0.112262,0.085987,-0.023003,-0.151592,-0.108893,-0.009504,-0.111104,0.170099
3,3,-0.186971,0.112337,-0.010057,0.114066,-0.043843,0.023473,-0.094416,-0.034772,-0.009186,...,0.065617,0.023958,-0.077597,0.094924,-0.026164,-0.149806,-0.128227,-0.046681,-0.124457,0.143542
4,4,-0.089071,0.038916,-0.012351,0.113045,-0.067452,-0.006399,-0.105726,-0.109937,0.010508,...,0.062809,0.050385,-0.114153,0.091296,-0.032458,-0.111222,-0.134111,-0.048697,-0.090511,0.148385

In [42]:
df4.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,758,759,760,761,762,763,764,765,766,767
0,0,0.251582,0.065441,0.036327,-0.683447,-0.864267,0.043688,-0.182814,-0.056845,0.180367,...,0.731047,0.057088,0.038299,0.289821,-0.283759,0.252248,0.018195,0.435494,-0.048739,0.023718
1,1,0.307343,0.046227,0.070979,-0.689943,-0.421657,-0.045189,0.146107,-0.190608,0.162453,...,0.758684,0.373472,0.056404,0.079221,-0.368649,0.135729,-0.081308,0.337456,0.157623,0.422735
2,2,0.330305,0.214742,0.517233,-0.529509,-0.374165,-0.236629,0.780357,-0.248850,0.348099,...,0.462937,0.052816,-0.340460,0.361714,-0.405706,0.020661,-0.041318,-0.035852,-0.298648,0.326292
3,3,0.266967,0.254776,0.249469,-0.518748,-0.460016,-0.099519,0.359582,0.087548,0.356397,...,0.631750,0.190572,0.242963,0.207410,-0.466586,-0.032446,0.130334,0.219458,0.072517,0.343598
4,4,0.221523,0.013097,-0.097723,-1.067212,-0.829449,0.143097,-0.051330,-0.085799,0.035921,...,0.565033,0.261153,-0.027681,0.528556,-0.489401,0.421287,-0.566908,0.184935,0.217472,0.156604

In [43]:
df6.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
df1.drop(df1.columns[[0]], axis=1, inplace=True)
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,-0.047231,0.015711,-0.071031,-0.007662,0.030991,0.059917,0.004687,-0.046487,0.107146,0.019806,...,-0.018673,0.030429,-0.016143,0.046663,0.034890,0.028259,-0.000247,-0.030757,0.008817,-0.006377
1,-0.098719,0.015418,-0.097384,-0.038516,0.043484,0.060653,0.018721,-0.041094,0.129638,0.026229,...,0.000181,0.017451,-0.012927,0.064079,0.031009,0.022566,0.020062,-0.025959,-0.026582,0.008801
2,-0.092993,0.026287,-0.107235,-0.050508,0.044317,0.051024,0.017439,-0.049028,0.143363,0.030728,...,0.016668,0.016611,-0.022086,0.065026,0.024556,0.032230,-0.003800,-0.040938,-0.027009,0.004288
3,-0.074855,0.020305,-0.100434,-0.031188,0.016835,0.047498,-0.001790,-0.055538,0.132829,0.042551,...,-0.001125,0.033835,-0.021322,0.058418,0.049020,0.035385,-0.014268,-0.031588,-0.023069,0.008638
4,-0.044288,0.022878,-0.035347,-0.002803,0.065113,0.079378,0.019056,-0.048419,0.116516,0.013675,...,-0.013225,0.046087,-0.002287,0.054631,-0.005369,0.021631,0.013978,-0.053094,0.023938,0.000747

In [45]:
df2.drop(df2.columns[[0]], axis=1, inplace=True)
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,-0.018407,0.085011,0.029703,-0.044558,-0.046228,0.002105,-0.017075,0.011753,0.039239,-0.341933,...,0.007392,-0.050867,-0.032619,-0.040177,0.003517,0.009812,0.033037,-0.059005,0.020749,0.040800
1,-0.061130,0.069028,0.029945,-0.075593,-0.055460,0.029755,-0.034010,0.027264,0.033029,-0.427923,...,0.003908,-0.056133,0.006894,0.011421,0.056875,0.074536,0.001674,-0.046282,-0.029717,-0.002265
2,-0.084698,0.059528,-0.019130,-0.054112,-0.039338,0.013001,-0.020171,0.000319,0.021646,-0.397745,...,-0.014100,-0.059806,0.025660,0.011339,0.019782,0.032892,0.005613,-0.029948,-0.029217,-0.031719
3,-0.049269,0.032437,-0.001154,-0.040035,-0.033356,0.029849,0.004792,0.000715,0.013032,-0.474486,...,-0.018463,-0.021215,0.019852,0.006229,0.031585,0.018694,0.036211,-0.089839,-0.007266,-0.009470
4,-0.090736,0.040478,0.054596,-0.015434,-0.090787,0.020753,0.070594,-0.048692,-0.019835,-0.276395,...,0.041861,-0.051594,0.042672,-0.065068,0.078107,0.028808,-0.011964,-0.095961,-0.040278,-0.061897

In [46]:
df3.drop(df3.columns[[0]], axis=1, inplace=True)
df3.head()

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,-0.132192,0.085008,-0.021770,0.104603,-0.064176,0.014193,-0.075376,-0.062582,0.017596,0.029619,...,0.057682,0.009523,-0.101325,0.114898,-0.016636,-0.134433,-0.144924,-0.050143,-0.100066,0.150123
1,-0.169962,0.117862,-0.023319,0.127086,-0.067426,0.011222,-0.069913,-0.051933,-0.023587,0.024029,...,0.068842,-0.015122,-0.104072,0.097132,-0.028843,-0.158527,-0.118772,-0.044826,-0.101228,0.156272
2,-0.178082,0.116493,0.005438,0.142175,-0.040640,0.008901,-0.113469,-0.031516,-0.040196,0.012933,...,0.087883,-0.034578,-0.112262,0.085987,-0.023003,-0.151592,-0.108893,-0.009504,-0.111104,0.170099
3,-0.186971,0.112337,-0.010057,0.114066,-0.043843,0.023473,-0.094416,-0.034772,-0.009186,0.032829,...,0.065617,0.023958,-0.077597,0.094924,-0.026164,-0.149806,-0.128227,-0.046681,-0.124457,0.143542
4,-0.089071,0.038916,-0.012351,0.113045,-0.067452,-0.006399,-0.105726,-0.109937,0.010508,0.025785,...,0.062809,0.050385,-0.114153,0.091296,-0.032458,-0.111222,-0.134111,-0.048697,-0.090511,0.148385

In [47]:
df4.drop(df4.columns[[0]], axis=1, inplace=True)
df4.head()

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.251582,0.065441,0.036327,-0.683447,-0.864267,0.043688,-0.182814,-0.056845,0.180367,-0.370679,...,0.731047,0.057088,0.038299,0.289821,-0.283759,0.252248,0.018195,0.435494,-0.048739,0.023718
1,0.307343,0.046227,0.070979,-0.689943,-0.421657,-0.045189,0.146107,-0.190608,0.162453,-0.529358,...,0.758684,0.373472,0.056404,0.079221,-0.368649,0.135729,-0.081308,0.337456,0.157623,0.422735
2,0.330305,0.214742,0.517233,-0.529509,-0.374165,-0.236629,0.780357,-0.248850,0.348099,-0.530329,...,0.462937,0.052816,-0.340460,0.361714,-0.405706,0.020661,-0.041318,-0.035852,-0.298648,0.326292
3,0.266967,0.254776,0.249469,-0.518748,-0.460016,-0.099519,0.359582,0.087548,0.356397,-0.599168,...,0.631750,0.190572,0.242963,0.207410,-0.466586,-0.032446,0.130334,0.219458,0.072517,0.343598
4,0.221523,0.013097,-0.097723,-1.067212,-0.829449,0.143097,-0.051330,-0.085799,0.035921,0.215113,...,0.565033,0.261153,-0.027681,0.528556,-0.489401,0.421287,-0.566908,0.184935,0.217472,0.156604

In [48]:
df6.drop(df6.columns[[0]], axis=1, inplace=True)
df6.head()

,0,1,2,3,4,5,6,7,8,9,...,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
df1['Level'] = df5['Level '].values
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,Level
0,-0.047231,0.015711,-0.071031,-0.007662,0.030991,0.059917,0.004687,-0.046487,0.107146,0.019806,...,0.030429,-0.016143,0.046663,0.034890,0.028259,-0.000247,-0.030757,0.008817,-0.006377,3
1,-0.098719,0.015418,-0.097384,-0.038516,0.043484,0.060653,0.018721,-0.041094,0.129638,0.026229,...,0.017451,-0.012927,0.064079,0.031009,0.022566,0.020062,-0.025959,-0.026582,0.008801,3
2,-0.092993,0.026287,-0.107235,-0.050508,0.044317,0.051024,0.017439,-0.049028,0.143363,0.030728,...,0.016611,-0.022086,0.065026,0.024556,0.032230,-0.003800,-0.040938,-0.027009,0.004288,3
3,-0.074855,0.020305,-0.100434,-0.031188,0.016835,0.047498,-0.001790,-0.055538,0.132829,0.042551,...,0.033835,-0.021322,0.058418,0.049020,0.035385,-0.014268,-0.031588,-0.023069,0.008638,3
4,-0.044288,0.022878,-0.035347,-0.002803,0.065113,0.079378,0.019056,-0.048419,0.116516,0.013675,...,0.046087,-0.002287,0.054631,-0.005369,0.021631,0.013978,-0.053094,0.023938,0.000747,1

In [50]:
df2['Level'] = df5['Level '].values
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,Level
0,-0.018407,0.085011,0.029703,-0.044558,-0.046228,0.002105,-0.017075,0.011753,0.039239,-0.341933,...,-0.050867,-0.032619,-0.040177,0.003517,0.009812,0.033037,-0.059005,0.020749,0.040800,3
1,-0.061130,0.069028,0.029945,-0.075593,-0.055460,0.029755,-0.034010,0.027264,0.033029,-0.427923,...,-0.056133,0.006894,0.011421,0.056875,0.074536,0.001674,-0.046282,-0.029717,-0.002265,3
2,-0.084698,0.059528,-0.019130,-0.054112,-0.039338,0.013001,-0.020171,0.000319,0.021646,-0.397745,...,-0.059806,0.025660,0.011339,0.019782,0.032892,0.005613,-0.029948,-0.029217,-0.031719,3
3,-0.049269,0.032437,-0.001154,-0.040035,-0.033356,0.029849,0.004792,0.000715,0.013032,-0.474486,...,-0.021215,0.019852,0.006229,0.031585,0.018694,0.036211,-0.089839,-0.007266,-0.009470,3
4,-0.090736,0.040478,0.054596,-0.015434,-0.090787,0.020753,0.070594,-0.048692,-0.019835,-0.276395,...,-0.051594,0.042672,-0.065068,0.078107,0.028808,-0.011964,-0.095961,-0.040278,-0.061897,1

In [51]:
df3['Level'] = df5['Level '].values
df3.head()

,0,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,Level
0,-0.132192,0.085008,-0.021770,0.104603,-0.064176,0.014193,-0.075376,-0.062582,0.017596,0.029619,...,0.009523,-0.101325,0.114898,-0.016636,-0.134433,-0.144924,-0.050143,-0.100066,0.150123,3
1,-0.169962,0.117862,-0.023319,0.127086,-0.067426,0.011222,-0.069913,-0.051933,-0.023587,0.024029,...,-0.015122,-0.104072,0.097132,-0.028843,-0.158527,-0.118772,-0.044826,-0.101228,0.156272,3
2,-0.178082,0.116493,0.005438,0.142175,-0.040640,0.008901,-0.113469,-0.031516,-0.040196,0.012933,...,-0.034578,-0.112262,0.085987,-0.023003,-0.151592,-0.108893,-0.009504,-0.111104,0.170099,3
3,-0.186971,0.112337,-0.010057,0.114066,-0.043843,0.023473,-0.094416,-0.034772,-0.009186,0.032829,...,0.023958,-0.077597,0.094924,-0.026164,-0.149806,-0.128227,-0.046681,-0.124457,0.143542,3
4,-0.089071,0.038916,-0.012351,0.113045,-0.067452,-0.006399,-0.105726,-0.109937,0.010508,0.025785,...,0.050385,-0.114153,0.091296,-0.032458,-0.111222,-0.134111,-0.048697,-0.090511,0.148385,1

In [52]:
df4['Level'] = df5['Level '].values
df4.head()

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,Level
0,0.251582,0.065441,0.036327,-0.683447,-0.864267,0.043688,-0.182814,-0.056845,0.180367,-0.370679,...,0.057088,0.038299,0.289821,-0.283759,0.252248,0.018195,0.435494,-0.048739,0.023718,3
1,0.307343,0.046227,0.070979,-0.689943,-0.421657,-0.045189,0.146107,-0.190608,0.162453,-0.529358,...,0.373472,0.056404,0.079221,-0.368649,0.135729,-0.081308,0.337456,0.157623,0.422735,3
2,0.330305,0.214742,0.517233,-0.529509,-0.374165,-0.236629,0.780357,-0.248850,0.348099,-0.530329,...,0.052816,-0.340460,0.361714,-0.405706,0.020661,-0.041318,-0.035852,-0.298648,0.326292,3
3,0.266967,0.254776,0.249469,-0.518748,-0.460016,-0.099519,0.359582,0.087548,0.356397,-0.599168,...,0.190572,0.242963,0.207410,-0.466586,-0.032446,0.130334,0.219458,0.072517,0.343598,3
4,0.221523,0.013097,-0.097723,-1.067212,-0.829449,0.143097,-0.051330,-0.085799,0.035921,0.215113,...,0.261153,-0.027681,0.528556,-0.489401,0.421287,-0.566908,0.184935,0.217472,0.156604,1

In [53]:
df6['Level'] = df5['Level '].values
df6.head()

,0,1,2,3,4,5,6,7,8,9,...,3595,3596,3597,3598,3599,3600,3601,3602,3603,Level
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [25]:
df1.to_csv('fasttext_changedlevels.csv')

In [26]:
df2.to_csv('glove_changedlevels.csv')

In [54]:
df3.to_csv('w2v_changedlevels.csv')

In [28]:
df4.to_csv('bert_changedlevels.csv')

In [55]:
df6.to_csv('tfidf_changedlevels.csv')