Smote_glove_features

In [ ]:
from google.colab import drive
from google.colab import files

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd  
import numpy as np 
from imblearn.over_sampling import SMOTE 
from sklearn.model_selection import KFold
from sklearn import metrics
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.preprocessing import MultiLabelBinarizer

**Models**

In [3]:
def Decision_tree_classifier(X_train, y_train, X_test, y_test):
  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(class_weight = "balanced")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("Decision Tree Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Decision Tree F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [4]:
def GNB_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  gnb = GaussianNB()

  #Train the model using the training sets
  gnb.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = gnb.predict(X_test)

  print("Gaussian Naive Bayes Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gaussian Naive Bayes F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [5]:
def KNN_classifier (X_train, y_train, X_test, y_test):
  #Create KNN Classifier
  knn = KNeighborsClassifier(n_neighbors=5)

  #Train the model using the training sets
  knn.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = knn.predict(X_test)

  print("KNN Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("KNN F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [6]:
def svm_classifier (X_train, y_train, X_test, y_test):
  #Create a Support Vector Machine Classifier
  clf = svm.SVC(kernel='linear', class_weight = "balanced") # Linear Kernel

  #Train the model using the training sets
  clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)

  print("SVM Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("SVM F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [7]:
def random_forest_classifier (X_train, y_train, X_test, y_test):
  #Create a Gaussian Classifier
  clf=RandomForestClassifier(n_estimators=100, class_weight = "balanced")

  #Train the model using the training sets y_pred=clf.predict(X_test)
  clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred=clf.predict(X_test)
  print("RF Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("RF F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [8]:
def ada_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  abc = AdaBoostClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = abc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Ada-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Ada-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [9]:
def gradient_boost_classifier (X_train, y_train, X_test, y_test):
  # Create adaboost classifer object
  gbc = GradientBoostingClassifier(n_estimators=50,
                          learning_rate=1)
  # Train Adaboost Classifer
  model = gbc.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)

  print("Gradient-Boost Accuracy:",metrics.accuracy_score(y_test, y_pred))
  print("Gradient-Boost F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

In [10]:
def perceptron_classifier (X_train, y_train, X_test, y_test):
  p = Perceptron(random_state=150)
  p.fit(X_train, y_train)
  predictions_train = p.predict(X_train)
  predictions_test = p.predict(X_test)
  train_score = accuracy_score(predictions_train, y_train)
  #print("score on train data: ", train_score)
  test_score = f1_score(predictions_test, y_test, average='weighted' )
  print("Perceptron F1 score:", test_score)

In [11]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smote_anova_glove/data.csv"
df3 = pd.read_csv(path)
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,Level 5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,Level 5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,Level 5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",Level 5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Level 2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [12]:
df3.iloc[:,1].replace(['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'],
                        [1, 2, 3, 4, 5], inplace=True)

In [13]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [14]:
#define bins
bins = [0,2,4,5]
#name of the group 
group_names = ['Low', 'Moderate', 'High']
df3['Level '] = pd.cut(df3["Level "],bins,labels = group_names)

In [15]:
df3.head(5)

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,High,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,High,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,High,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",High,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Low,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [16]:
df3['Level '] = df3['Level '].map({'Low': 1, 'Moderate': 2, 'High': 3}).astype(int)

In [17]:
df3.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,3,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,3,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,3,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",3,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,1,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

In [18]:
import pandas as pd
path = "/content/drive/MyDrive/newpro/threeclass_problem/smote_anova_glove/glove_withstopwordchangelevels_150_features.csv"
df2 = pd.read_csv(path)
df2.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,140,141,142,143,144,145,146,147,148,149
0,0,-0.171773,0.407910,-0.456866,-0.091159,0.721801,-0.586783,0.320243,-0.195638,0.165933,...,0.012634,0.011752,-0.787087,0.064079,-1.798244,-0.617244,-0.914053,1.188296,-0.880736,-0.534243
1,1,-0.733700,-0.400838,-1.174874,-0.508074,0.794512,-0.436028,-0.257079,-0.229393,-0.764310,...,-0.223658,-0.682725,0.082059,0.421716,0.742120,-1.015367,0.022995,0.936226,-1.112095,0.609846
2,2,1.952276,0.652616,-1.269276,2.613370,-2.907918,-4.462420,2.565279,-0.552830,1.818557,...,0.687696,1.311867,-0.140812,1.282942,1.789732,0.485420,-2.732210,-2.293142,0.024363,2.117748
3,3,0.301589,1.748069,-2.376656,0.752863,-2.222344,-2.110461,1.483469,0.536828,1.083604,...,-1.426691,2.256543,1.883721,0.583754,-0.639666,0.687385,-0.778197,-1.550622,-1.094035,2.331273
4,4,0.056613,-0.580228,-0.502394,-0.574062,-0.083692,0.565413,0.260441,0.068242,-0.042237,...,0.260626,-0.368202,-0.008389,0.734563,-0.994221,-0.000412,0.426007,0.886173,-1.153448,-0.148463

In [19]:
df2.drop(df2.columns[[0]], axis=1, inplace=True)
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
0,-0.171773,0.407910,-0.456866,-0.091159,0.721801,-0.586783,0.320243,-0.195638,0.165933,-0.382628,...,0.012634,0.011752,-0.787087,0.064079,-1.798244,-0.617244,-0.914053,1.188296,-0.880736,-0.534243
1,-0.733700,-0.400838,-1.174874,-0.508074,0.794512,-0.436028,-0.257079,-0.229393,-0.764310,-0.775397,...,-0.223658,-0.682725,0.082059,0.421716,0.742120,-1.015367,0.022995,0.936226,-1.112095,0.609846
2,1.952276,0.652616,-1.269276,2.613370,-2.907918,-4.462420,2.565279,-0.552830,1.818557,1.378403,...,0.687696,1.311867,-0.140812,1.282942,1.789732,0.485420,-2.732210,-2.293142,0.024363,2.117748
3,0.301589,1.748069,-2.376656,0.752863,-2.222344,-2.110461,1.483469,0.536828,1.083604,-1.751125,...,-1.426691,2.256543,1.883721,0.583754,-0.639666,0.687385,-0.778197,-1.550622,-1.094035,2.331273
4,0.056613,-0.580228,-0.502394,-0.574062,-0.083692,0.565413,0.260441,0.068242,-0.042237,-0.090916,...,0.260626,-0.368202,-0.008389,0.734563,-0.994221,-0.000412,0.426007,0.886173,-1.153448,-0.148463

In [20]:
df2['Level'] = df3['Level '].values
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,141,142,143,144,145,146,147,148,149,Level
0,-0.171773,0.407910,-0.456866,-0.091159,0.721801,-0.586783,0.320243,-0.195638,0.165933,-0.382628,...,0.011752,-0.787087,0.064079,-1.798244,-0.617244,-0.914053,1.188296,-0.880736,-0.534243,3
1,-0.733700,-0.400838,-1.174874,-0.508074,0.794512,-0.436028,-0.257079,-0.229393,-0.764310,-0.775397,...,-0.682725,0.082059,0.421716,0.742120,-1.015367,0.022995,0.936226,-1.112095,0.609846,3
2,1.952276,0.652616,-1.269276,2.613370,-2.907918,-4.462420,2.565279,-0.552830,1.818557,1.378403,...,1.311867,-0.140812,1.282942,1.789732,0.485420,-2.732210,-2.293142,0.024363,2.117748,3
3,0.301589,1.748069,-2.376656,0.752863,-2.222344,-2.110461,1.483469,0.536828,1.083604,-1.751125,...,2.256543,1.883721,0.583754,-0.639666,0.687385,-0.778197,-1.550622,-1.094035,2.331273,3
4,0.056613,-0.580228,-0.502394,-0.574062,-0.083692,0.565413,0.260441,0.068242,-0.042237,-0.090916,...,-0.368202,-0.008389,0.734563,-0.994221,-0.000412,0.426007,0.886173,-1.153448,-0.148463,1

In [21]:
 #Data Shuffling
df2 = df2.sample(frac = 1) #frac denotes the fraction of samples to be returned. 

 
#train-test split
trdata = df2.sample(frac=0.7, random_state=25) #Training data = 70%
tsdata = df2.drop(trdata.index) #Testing data = 30%
X_train = trdata.iloc[:,:-1]
y_train = trdata.iloc[:,-1]
X_test = tsdata.iloc[:,:-1]
y_test = tsdata.iloc[:,-1]

#SMOTE
sm = SMOTE()
X_train, y_train = sm.fit_resample(X_train, y_train.ravel())

In [22]:
  #Model Calling
  Decision_tree_classifier(X_train, y_train, X_test, y_test)
  GNB_classifier(X_train, y_train, X_test, y_test)
  KNN_classifier(X_train, y_train, X_test, y_test) 
  svm_classifier(X_train, y_train, X_test, y_test)
  random_forest_classifier(X_train, y_train, X_test, y_test)
  ada_boost_classifier(X_train, y_train, X_test, y_test)
  gradient_boost_classifier(X_train, y_train, X_test, y_test)
  perceptron_classifier(X_train, y_train, X_test, y_test)

Decision Tree Accuracy: 0.38049713193116635
Decision Tree F1 Score: 0.37733628159026433
Gaussian Naive Bayes Accuracy: 0.33078393881453155
Gaussian Naive Bayes F1 Score: 0.3065689970654482
KNN Accuracy: 0.29636711281070743
KNN F1 Score: 0.29270818068173815
SVM Accuracy: 0.30975143403441685
SVM F1 Score: 0.3109005810598308
RF Accuracy: 0.40344168260038243
RF F1 Score: 0.38450300328081344
Ada-Boost Accuracy: 0.3479923518164436
Ada-Boost F1 Score: 0.35172036452341127
Gradient-Boost Accuracy: 0.3441682600382409
Gradient-Boost F1 Score: 0.34058119848730517
Perceptron F1 score: 0.30125168598802493